=== JonathanRakotomalala/cabinetinfirmier/ConsoleApp1/data/xsd/cabinet.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:me="http://www.univ-grenoble-alpes.fr/l3miage/medical"
           targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/medical"
           elementFormDefault="qualified"
>
    <!-- Element racine -->
    <xs:element name="infirmiers" type ="me:Infirmiers"/>
    <xs:element name="adresse" type="me:Adressepatient" />
    <xs:element name="cabinet" type="me:Cabinet">
        <xs:key name="uniqueId">
            <xs:selector xpath="me:infirmiers/me:infirmier"/>
            <xs:field xpath="me:id"/>
        </xs:key>
        <xs:keyref name="idExist" refer="me:uniqueId">
            <xs:selector xpath="me:patients/me:patient/me:visite"/>
            <xs:field xpath="me:intervenant"/>
        </xs:keyref>
    </xs:element>

    <xs:complexType name="Cabinet">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="adresse" type="me:Adresse"/>
            <xs:element name="infirmiers" type="me:Infirmiers"/>
            <xs:element name="patients" type="me:Patients"/>
        </xs:sequence>
    </xs:complexType>

    <!-- adresse -->
    <xs:complexType name="Adresse" >
        <xs:sequence>
            <xs:element name="numero" type="me:posint" />
            <xs:element name="rue" type="xs:string"/>
            <xs:element name="codePostal" type="me:CodePostal"/>
            <xs:element name="ville" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Adressepatient" >
        <xs:sequence>
            <xs:element name="etage" type="me:posint" minOccurs="0"/>
            <xs:element name="numero" type="me:posint" minOccurs="0"/>
            <xs:element name="rue" type="xs:string"/>
            <xs:element name="ville" type="xs:string"/>
            <xs:element name="codePostal" type="me:CodePostal"/>
        </xs:sequence>
    </xs:complexType>



    <!-- Infirmier -->
    <xs:complexType name="Infirmier">
        <xs:sequence>
            <xs:element name="id" type="me:Id"/>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prénom" type ="xs:string"/>
            <xs:element name="photo" type="me:Photo"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Patient -->
    <xs:complexType name="Patient">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prénom" type="xs:string"/>
            <xs:element name="sexe" type="me:Sexe"/>
            <xs:element name="naissance" type="xs:date"/>
            <xs:element name="numero" type="me:Numsoc"/>
            <xs:element name="adresse" type="me:Adressepatient"/>
            <xs:element name="visite" type="me:Visite"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Visite -->
    <xs:complexType name="Visite">
        <xs:sequence>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="intervenant" type="me:Id" minOccurs="0"/>
            <xs:element name="acte" type="me:acteid" maxOccurs="10"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Infirmiers -->
    <xs:complexType name="Infirmiers">
        <xs:sequence>
            <xs:element name="infirmier" type="me:Infirmier" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Patients -->
    <xs:complexType name="Patients">
        <xs:sequence>
            <xs:element name="patient" type="me:Patient" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="posint">
        <xs:restriction base="xs:int">
            <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- acte -->
    <xs:complexType name="acteid">
        <xs:attribute name="id" type="me:Acteid"/>
    </xs:complexType>

    <xs:simpleType name="Acteid">
        <xs:restriction base="xs:string">
            <xs:pattern value="10[1-9]|11[0-3]|20[0-4]|[34]0[0-3]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Coef">
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9]|([1-9].[1-9])"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Typeacte">
        <xs:restriction base="xs:string">
            <xs:enumeration value="pi"/>
            <xs:enumeration value="pc"/>
            <xs:enumeration value="pl"/>
            <xs:enumeration value="sd"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Cle">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AMI"/>
            <xs:enumeration value="DI"/>
            <xs:enumeration value="AIS"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Sexe -->
    <xs:simpleType name="Sexe">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M"/>
            <xs:enumeration value="F"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Identifiant infirmier -->
    <xs:simpleType name="Id">
        <xs:restriction base="xs:int">
            <xs:pattern value="[0-9][0-9][1-9]"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Code postal -->
    <xs:simpleType name="CodePostal">
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9][0-9][0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Num securite sociale -->
    <xs:simpleType name="Numsoc">
        <xs:restriction base="xs:string">
            <xs:pattern value="[12][0-9]{2}(0[1-9]|1[0-2])(2[AB]|[0-9]{2})[0-9]{3}[0-9]{3}([0-9]{2})"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Photo">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]*[.]png"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== JonathanRakotomalala/cabinetinfirmier/ConsoleApp1/data/xml/Infirmiers.xml
<?xml version="1.0" encoding="utf-8"?>
<infirmiers xmlns="http://www.univ-grenoble-alpes.fr/l3miage/medical"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/medical ../xsd/cabinet.xsd">
    <infirmier>
        <id>001</id>
        <nom>Fréchie</nom>
        <prénom>Sarah</prénom>
        <photo>sarah.png</photo>
    </infirmier>
    <infirmier>
        <id>002</id>
        <nom>Stické</nom>
        <prénom>Sophie</prénom>
        <photo>sophie.png</photo>
    </infirmier>
    <infirmier>
        <id>003</id>
        <nom>Ochon</nom>
        <prénom>Paul</prénom>
        <photo>paul.png</photo>
    </infirmier>
</infirmiers>

=== JonathanRakotomalala/cabinetinfirmier/ConsoleApp1/data/xml/cabinet.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<cabinet xmlns="http://www.univ-grenoble-alpes.fr/l3miage/medical" 
         xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/medical ../xsd/cabinet.xsd" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <nom>Soins à Grenoble</nom>
    <adresse>
        <numero>60</numero>
        <rue>rue de la Chimie</rue>
        <codePostal>38041</codePostal>
        <ville>Grenoble</ville>
    </adresse>
    <infirmiers>
        <infirmier>
            <id>001</id>
            <nom>Fréchie</nom>
            <prénom>Sarah</prénom>
            <photo>sarah.png</photo>
        </infirmier>
        <infirmier>
            <id>002</id>
            <nom>Stické</nom>
            <prénom>Sophie</prénom>
            <photo>sophie.png</photo>
        </infirmier>
        <infirmier>
            <id>003</id>
            <nom>Ochon</nom>
            <prénom>Paul</prénom>
            <photo>paul.png</photo>
        </infirmier>        
    </infirmiers>
    <patients>
        <!-- Homme né en août 98 en France à Marseille (n°55 en Bouche du Rhône) 458e naissance-->
        <patient>
            <nom>Alécole</nom>
            <prénom>Yvon</prénom>
            <sexe>M</sexe>
            <naissance>1998-08-22</naissance>
            <numero>198082205545852</numero>
            <adresse>
                <etage>6</etage>
                <numero>50</numero>
                <rue>avenue Félix Viallet</rue>
                <ville>Grenoble</ville>
                <codePostal>38031</codePostal>
            </adresse>
            <visite>
                <date>2015-12-08</date>
                <intervenant>001</intervenant>
                <acte id="109"/>
            </visite>
        </patient>
        <!-- Femme née le 08 mars 82 en France, à Lyon (n° 23 dans le rhône), il s’agissait de la 52e
naissance dans cette ville-->
        <patient>
            <nom>Orouge</nom>
            <prénom>Elvire</prénom>
            <sexe>F</sexe>
            <naissance>1982-03-08</naissance>
            <numero>282030802305201</numero>
            <adresse>
                <rue>: Rond-Point de la Croix de Vie</rue>
                <ville>La Tronche</ville>
                <codePostal>38700</codePostal>
            </adresse>
            <visite>
                <date>2015-12-08</date>
                <acte id="300"/>
            </visite>
        </patient>
        <!-- homme née le 25 mars 75 en France, à Chambéry (n° 65 dans la Savoie) 692e naissance.-->
        <patient>
            <nom>Pien</nom>
            <prénom>Oscare</prénom>
            <sexe>M</sexe>
            <naissance>1975-03-25</naissance>
            <numero>175032506569210</numero>
            <adresse>
                <rue>rue Casimir Brenier</rue>
                <ville>Grenoble</ville>
                <codePostal>38000</codePostal>
            </adresse>
            <visite>
                <date>2015-12-08</date>
                <intervenant>002</intervenant>
                <acte id="101"/>
                <acte id="104" />
            </visite>
        </patient> 
        <!-- un petit garçon, né le 02 août 2011 en France, à Bordeaux(n° 63 dans la Gironde).35e naissance.-->
        <patient>
            <nom>Kapoëtla</nom>
            <prénom>Xavier</prénom>
            <sexe>M</sexe>
            <naissance>2011-08-02</naissance>
            <numero>111080206303582</numero>
            <adresse>
                <numero>25</numero>
                <rue>rue des Martyrs</rue>
                <ville>Grenoble</ville>
                <codePostal>38042</codePostal>
            </adresse>
            <visite>
                <date>2015-12-08</date>
                <intervenant>003</intervenant>
                <acte id="111"/>
            </visite>
        </patient>
    </patients>
</cabinet>
